import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";
import Footers from "./components/Footer";
import { auth } from "../../auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="flex gap-4">
            <Link href={"/"}>Home</Link>
            <Link href={"/add-books"}>add</Link>
          <Navbar session={session} />
            </nav>
        </header>
        <main>{children}</main>
        <footer>
          <Footers/>
        </footer>
      </body>
    </html>
  );
}
